[package]
name = "titan-types"
version.workspace = true
authors.workspace = true
description = "..."
categories = ["rust-patterns"]
homepage = "https://github.com/oovm/RustTemplate"
repository = "https://github.com/oovm/RustTemplate"
documentation = "https://docs.rs/sub_projects"
readme = "readme.md"
license.workspace = true
edition.workspace = true
exclude = ["package.json", "tests/**"]

[dependencies]
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
