export const API_SCHEMA_VERSION = 1
export type DeploymentTarget = 'native' | 'wasm'
export type ManifestState = 'ready' | 'missing' | 'invalid'
export type RunHealth = 'healthy' | 'degraded' | 'failed' | 'unknown'
export type ModelDescriptor = { family: string; variant: string; schema: { input: string; output: string; version: number }; capabilities: { training: boolean; generation: boolean; streaming: boolean; native: boolean; wasm: boolean }; manifest: { schema_version: number; state: ManifestState; deployment_targets: DeploymentTarget[] }; diagnostic_summary: string }
export type RunSummary = { run_id: string; model: ModelDescriptor; step: number | null; rank: number | null; graph_version: string | null; health: RunHealth; health_summary: string }
type ApiEnvelope<T> = { schema_version: number; request_id: string; generated_at: string; data: T }
type ApiFailure = { schema_version: number; request_id: string; code: string; message: string; retryable: boolean }
export type ApiFailureKind = 'offline' | 'http' | 'protocol' | 'aborted'
export class ApiClientError extends Error { constructor(public readonly kind: ApiFailureKind, message: string, public readonly status?: number, public readonly requestId?: string) { super(message); this.name = 'ApiClientError' } }
function record(value: unknown): Record<string, unknown> | undefined { return typeof value === 'object' && value !== null ? value as Record<string, unknown> : undefined }
function parseEnvelope<T>(body: unknown, validData: (data: unknown) => data is T): ApiEnvelope<T> { const value = record(body); if (!value || value.schema_version !== API_SCHEMA_VERSION || typeof value.request_id !== 'string' || typeof value.generated_at !== 'string' || !validData(value.data)) throw new ApiClientError('protocol', 'API response does not satisfy schema version 1'); return value as ApiEnvelope<T> }
function isModel(value: unknown): value is ModelDescriptor { const model = record(value); const schema = record(model?.schema); const manifest = record(model?.manifest); const capabilities = record(model?.capabilities); return !!model && typeof model.family === 'string' && typeof model.variant === 'string' && !!schema && typeof schema.version === 'number' && typeof schema.input === 'string' && typeof schema.output === 'string' && !!manifest && typeof manifest.schema_version === 'number' && Array.isArray(manifest.deployment_targets) && !!capabilities && typeof capabilities.native === 'boolean' && typeof model.diagnostic_summary === 'string' }
function isRun(value: unknown): value is RunSummary { const run = record(value); return !!run && typeof run.run_id === 'string' && isModel(run.model) && typeof run.health === 'string' && typeof run.health_summary === 'string' && (typeof run.step === 'number' || run.step === null) && (typeof run.rank === 'number' || run.rank === null) && (typeof run.graph_version === 'string' || run.graph_version === null) }
async function read<T>(path: string, validData: (data: unknown) => data is T, signal?: AbortSignal): Promise<T> { let response: Response; try { response = await fetch(path, { signal, headers: { accept: 'application/json' } }) } catch (error) { if (error instanceof DOMException && error.name === 'AbortError') throw new ApiClientError('aborted', 'Request cancelled'); throw new ApiClientError('offline', 'Network or API server is unavailable') }; const body: unknown = await response.json().catch(() => undefined); if (!response.ok) { const failure = record(body) as Partial<ApiFailure> | undefined; throw new ApiClientError('http', typeof failure?.message === 'string' ? failure.message : `API request failed (${response.status})`, response.status, typeof failure?.request_id === 'string' ? failure.request_id : undefined) }; return parseEnvelope(body, validData).data }
export function getModels(signal?: AbortSignal): Promise<ModelDescriptor[]> { return read('/api/models', (data): data is ModelDescriptor[] => Array.isArray(data) && data.every(isModel), signal) }
export function getRun(runId: string, signal?: AbortSignal): Promise<RunSummary> { return read(`/api/runs/${encodeURIComponent(runId)}`, isRun, signal) }
