<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue'
import { ApiClientError, getModels, getRun, type ModelDescriptor, type RunSummary } from './api'
const models = ref<ModelDescriptor[]>([]); const run = ref<RunSummary>(); const runId = ref(''); const loadingModels = ref(false); const loadingRun = ref(false); const status = ref('No API request has been made'); let controller: AbortController | undefined
const isConnected = computed(() => !status.value.startsWith('Offline') && !status.value.startsWith('HTTP') && !status.value.startsWith('Protocol'))
function beginRequest() { controller?.abort(); controller = new AbortController(); return controller.signal }
function describeError(error: unknown) { if (error instanceof ApiClientError) { if (error.kind === 'offline') return 'Offline: network or API server is unavailable'; if (error.kind === 'protocol') return `Protocol: ${error.message}`; if (error.kind === 'http') return `HTTP ${error.status}: ${error.message}${error.requestId ? ` (request ${error.requestId})` : ''}`; return 'Request cancelled' } return 'Unexpected client error' }
async function refreshModels() { loadingModels.value = true; try { models.value = await getModels(beginRequest()); status.value = `${models.value.length} model descriptors loaded` } catch (error) { status.value = describeError(error) } finally { loadingModels.value = false } }
async function loadRun() { if (!runId.value.trim()) { status.value = 'Enter a run identifier'; return }; loadingRun.value = true; try { run.value = await getRun(runId.value.trim(), beginRequest()); status.value = `Run ${run.value.run_id} loaded` } catch (error) { status.value = describeError(error) } finally { loadingRun.value = false } }
onBeforeUnmount(() => controller?.abort())
</script>
<template>
  <main><header><div><p class="eyebrow">Titan.rs / Read-only observability</p><h1>Model Directory</h1></div><div class="connection"><span :class="['dot', { offline: !isConnected }]" /> {{ isConnected ? 'API reachable' : 'API unavailable' }}</div></header>
    <section class="toolbar" aria-label="Read-only API queries"><button :disabled="loadingModels" @click="refreshModels">{{ loadingModels ? 'Loading models...' : 'Refresh models' }}</button><form @submit.prevent="loadRun"><label for="run-id">Run ID</label><input id="run-id" v-model="runId" placeholder="run-123" /><button :disabled="loadingRun" type="submit">{{ loadingRun ? 'Loading run...' : 'Load run' }}</button></form></section><p class="api-status" role="status">{{ status }}</p>
    <section class="content"><section class="panel wide"><div class="panel-title"><h2>Registered Models</h2><small>GET /api/models</small></div><p v-if="!models.length" class="empty">Refresh to request the model directory.</p><div v-else class="artifacts"><article v-for="model in models" :key="`${model.family}/${model.variant}`"><span :class="['status', model.manifest.state]">{{ model.manifest.state }}</span><strong>{{ model.family }} / {{ model.variant }}</strong><small>schema {{ model.schema.version }} · manifest {{ model.manifest.schema_version }}</small><small>targets: {{ model.manifest.deployment_targets.join(', ') }}</small><small>{{ model.diagnostic_summary }}</small></article></div></section>
      <section class="panel wide"><div class="panel-title"><h2>Run Health</h2><small>GET /api/runs/{id}</small></div><p v-if="!run" class="empty">Load a caller-visible run ID to inspect its latest read-only status.</p><dl v-else><dt>Model</dt><dd>{{ run.model.family }} / {{ run.model.variant }}</dd><dt>Health</dt><dd :class="run.health">{{ run.health }}</dd><dt>Step</dt><dd>{{ run.step ?? 'not reported' }}</dd><dt>Rank</dt><dd>{{ run.rank ?? 'not reported' }}</dd><dt>Graph version</dt><dd>{{ run.graph_version ?? 'not reported' }}</dd><dt>Summary</dt><dd>{{ run.health_summary }}</dd></dl></section></section>
  </main>
</template>
